language: c
script: ./debprootstrap $D_ARCH $D_SUITE 
matrix:
  include:
    - env: D_ARCH="amd64"
    - env: D_ARCH="i386"
    - env: D_ARCH="armhf"
    - env: D_SUITE="stable"
    - env: D_SUITE="testing"
    - env: D_SUITE="unstable"
deploy:
  provider: releases
  api_key:
    secure: DBH/AEBlDvcM6Uv5UrDXpzbf+HU0f3tctLoYGC8+dhtfF7Uihu8fZrtT5u2Z6MVEOcxTBI8EBHzvrtiJtkGGQu0yQPUzU89Dgtaa23HBu1RFLq0i5aqTWqmj60XpemBqyJxgUAYQnJubNeeinDBFYIo4IXFfBaM2qBM+9sECEo8=
  file_glob: true
  file: "*.bundle"
  on:
    repo: gboddin/debprootstrap
    tags: true
