language: c
before_install:
 - sudo apt-get update 
 - sudo apt-get install qemu-user
script: ./debprootstrap $D_ARCH $D_SUITE 
deploy:
  provider: releases
  api_key:
    secure: DBH/AEBlDvcM6Uv5UrDXpzbf+HU0f3tctLoYGC8+dhtfF7Uihu8fZrtT5u2Z6MVEOcxTBI8EBHzvrtiJtkGGQu0yQPUzU89Dgtaa23HBu1RFLq0i5aqTWqmj60XpemBqyJxgUAYQnJubNeeinDBFYIo4IXFfBaM2qBM+9sECEo8=
  file_glob: true
  file: "*.bundle"
  on:
    repo: gboddin/debprootstrap
    tags: true
matrix:
  include:
    - env: D_ARCH="armhf" D_SUITE="stretch"
    - env: D_ARCH="armhf" D_SUITE="jessie"
    - env: D_ARCH="armhf" D_SUITE="sid"
    - env: D_ARCH="armhf" D_SUITE="xenial"
    - env: D_ARCH="armhf" D_SUITE="trusty"
    - env: D_ARCH="armhf" D_SUITE="precise"
    - env: D_ARCH="amd64" D_SUITE="stretch"
    - env: D_ARCH="amd64" D_SUITE="jessie"
    - env: D_ARCH="amd64" D_SUITE="sid"
    - env: D_ARCH="amd64" D_SUITE="xenial"
    - env: D_ARCH="amd64" D_SUITE="trusty"
    - env: D_ARCH="amd64" D_SUITE="precise"
    - env: D_ARCH="i386" D_SUITE="wheezy"
    - env: D_ARCH="i386" D_SUITE="jessie"
    - env: D_ARCH="i386" D_SUITE="sid"
    - env: D_ARCH="i386" D_SUITE="xenial"
    - env: D_ARCH="i386" D_SUITE="trusty"
    - env: D_ARCH="i386" D_SUITE="precise"
