#!/bin/bash
CONTAINER_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd ${CONTAINER_PATH}
. lib/guest-tools/debproot.functions
PROOT=lib/guest-tools/proot
case $1 in
  user)
    shift
    $PROOT -b /home -b /dev -b /sys -b /proc -b /etc/resolv.conf -b /etc/hostname -r ${CONTAINER_PATH} $@
  ;;
  admin)
    shift
    HOME=/root SHELL=/bin/bash PATH=/bin:/sbin:/usr/sbin:/usr/bin $PROOT -w /root -b /etc/resolv.conf -b /etc/hostname -b /dev -b /sys -b /proc -r ${CONTAINER_PATH} -0 $@
  ;;
  saltstrap)
    [ -d ${CONTAINER_PATH}/srv/salt ] && echo "Already saltstraped" && exit 1
    [ -z $2 ] && echo "Please specify a git Salt tree" && exit 1
    RECIPE_URI=$2
    # install salt if not done :
    if ! ${CONTAINER_PATH}/manage user dpkg -l|grep -q salt-common ; then
        wget -O ${CONTAINER_PATH}/lib/guest-tools/saltstack-install.sh https://bootstrap.saltstack.com
        chmod +x ${CONTAINER_PATH}/lib/guest-tools/saltstack-install.sh
        ${CONTAINER_PATH}/manage admin /lib/guest-tools/saltstack-install.sh
    fi
    git clone $2 ${CONTAINER_PATH}/srv
    ${CONTAINER_PATH}/manage admin salt-call --local state.highstate
    ;;
  saltup)
    if ! ${CONTAINER_PATH}/manage user dpkg -l|grep -q salt-common ; then
        echo "Salt is not installed, use saltstrap"
        exit 1
    fi
    cd ${CONTAINER_PATH}/srv/salt
    git pull
    ${CONTAINER_PATH}/manage admin salt-call --local state.highstate
    ;;
  *)
  echo "Not implemented"
  ;;
esac

