#!/bin/bash

#remove makedev from package to install because we dont need to makedev ;)
rm /var/cache/bootstrap/makedev*deb
rm /var/cache/bootstrap/systemd*deb

echo Fuck off dbus ...
rm  /var/cache/bootstrap/*dbus*.deb
echo DPKG 2 starting ...
DEBIAN_FRONTEND="noninteractive" dpkg   --force-confdef --force-depends -Ei /var/cache/bootstrap/*.deb

# now post dpkg bug fixing :

# disable chfn bugs
cat /dev/null > /usr/bin/chfn
# base-files is left misconfigured sometimes FORCE clean package tree by bypassing buggy postinst :
[ -f /var/lib/dpkg/info/base-files.postinst ] && \
    echo "Fixing base-files bug now ..." && \
    rm /var/lib/dpkg/info/base-files.postinst

#last force after dpkg bug fixing :
apt-get install -f -y

#and clean
rm -Rf /var/cache/bootstrap 
rm -Rf /debootstrap
apt-get clean
echo "APT::Get::Install-Recommends \"false\";" >> /etc/apt/apt.conf.d/99norecommends.conf
echo "APT::Get::Install-Suggests \"false\";" >> /etc/apt/apt.conf.d/99norecommends.conf
