#!/bin/bash
CONTAINER_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd ${CONTAINER_PATH}

HOME=/root PATH=${PATH}:/sbin:/usr/sbin:/usr/local/sbin \
    ./proot -w /root -b /etc/hostname -b /etc/resolv.conf -b /etc/localtime \
      -b /dev -b /sys -b /proc -r ${CONTAINER_PATH} -0 -- ${COMMAND}
